# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroDeconvolution', '0003_auto_20160713_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='imfile',
            field=models.ImageField(upload_to='images/uploaded/%Y/%m/%d'),
        ),
    ]
