# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroDeconvolution', '0004_auto_20160717_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imfile', models.ImageField(upload_to='images/singleuse/%Y/%m/%d')),
            ],
        ),
    ]
