# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroDeconvolution', '0005_singleupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputRW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_image', models.ImageField(default='NULL', upload_to='images/singleuse/output/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='singleupload',
            name='imfile',
        ),
        migrations.AddField(
            model_name='singleupload',
            name='single_image',
            field=models.ImageField(default='NULL', upload_to='images/singleuse/uploaded/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='imfile',
            field=models.ImageField(default='NULL', upload_to='images/uploaded/%Y/%m/%d'),
        ),
    ]
