# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroDeconvolution', '0006_auto_20160730_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutputRW',
        ),
        migrations.AddField(
            model_name='singleupload',
            name='output_image',
            field=models.ImageField(default='NULL', upload_to='images/singleuse/output/%Y/%m/%d'),
        ),
    ]
