# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MicroDeconvolution', '0007_auto_20160730_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleUpload',
        ),
    ]
