# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroDeconvolution', '0008_delete_singleupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='imfile',
            field=models.ImageField(default='NULL', upload_to='images/processed/%Y/%m/%d'),
        ),
    ]
