# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroDeconvolution', '0009_auto_20160730_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='imfile',
            field=models.ImageField(default='NULL', upload_to='images/processed/'),
        ),
    ]
